### ISSUE TITLE
Is this for android?

### ISSUE THREAD

**Issue by Dungeonscats** [c10udburst-discord/Aliucord-RightNow-Plugins#1]
?

**Comment by C10udburst** [comment]
yes, for the yet-to-be-released [new react native version](https://github.com/Aliucord/AliucordRN).

**Comment by Dungeonscats** [comment]
+ I'm confused? how do I install aliucordrn?

**Comment by C10udburst** [comment]
You could read their [README](https://github.com/Aliucord/AliucordRN#readme=).

> Aliucord Rewrite for the new Discord React Native alpha. Unfinished for now, you should probably not install this if you don't know what you're doing.

and

> Install the apks pinned in the hermes thread on the Aliucord Server
> Run `pnpm serve` and start the app
