### ISSUE TITLE
Hidden Channels doesn't like group dms

### ISSUE THREAD

**Issue by greysilly7** [c10udburst-discord/Aliucord-RightNow-Plugins#15]
![Screenshot_20221017-084908_Aliucord.png](https://user-images.githubusercontent.com/65827291/196181269-6db6d608-64c5-4622-b5a8-d9a0083a12bc.png)

**Comment by C10udburst** [comment]
should be fixed now, please try

**Comment by greysilly7** [comment]
Yup, it's fixed now, thanks!!
